version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
      - cache
    environment:
      - MONGODB_URI=mongodb://database:27017/esx
      - REDIS_URL=redis://cache:6379
    networks:
      - app-network

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - app-network

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



