version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - app-network
    hostname: frontend  
    depends_on:
      - backend
    
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    hostname: backend
    environment:
      - MONGODB_URI=mongodb://database:27017/esx
      - REDIS_URL=redis://cache:6379
    depends_on:
      - database
      - cache

  database:
    image: mongo:latest
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - app-network

  cache:
    image: redis:latest
    networks:
      - app-network

  

networks:
  app-network:
    driver: bridge

